#!/usr/bin/env python3
"""Small, cautious HTTP load runner for RoundTable.

This is intentionally not a stress-test framework. It creates tickets through
the real web API with bounded concurrency and stops early when latency or error
rate crosses the configured safety thresholds.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import re
import statistics
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Iterable

import httpx


CSRF_RE = re.compile(r'name="csrf_token"\s+value="([^"]+)"')
PROJECT_KEY_RE = re.compile(r"^[A-Z][A-Z0-9]{1,9}$")


@dataclass(frozen=True)
class Stage:
    concurrency: int
    tickets: int


@dataclass
class StageResult:
    stage: Stage
    ok: int = 0
    errors: int = 0
    latencies_ms: list[float] | None = None

    def __post_init__(self) -> None:
        if self.latencies_ms is None:
            self.latencies_ms = []

    @property
    def total(self) -> int:
        return self.ok + self.errors

    @property
    def error_rate(self) -> float:
        return self.errors / self.total if self.total else 0.0

    @property
    def p95_ms(self) -> float:
        values = sorted(self.latencies_ms or [])
        if not values:
            return 0.0
        index = min(len(values) - 1, int(round((len(values) - 1) * 0.95)))
        return values[index]

    @property
    def avg_ms(self) -> float:
        return statistics.fmean(self.latencies_ms or [0.0])


def parse_stages(raw: str) -> list[Stage]:
    stages: list[Stage] = []
    for part in raw.split(","):
        clean = part.strip().lower()
        if not clean:
            continue
        if "x" in clean:
            left, right = clean.split("x", 1)
        elif ":" in clean:
            left, right = clean.split(":", 1)
        else:
            raise argparse.ArgumentTypeError("Stages must look like 1x10,2x25")
        try:
            concurrency = int(left)
            tickets = int(right)
        except ValueError as exc:
            raise argparse.ArgumentTypeError("Stage values must be integers") from exc
        if concurrency < 1 or tickets < 1:
            raise argparse.ArgumentTypeError("Stage values must be positive")
        stages.append(Stage(concurrency=concurrency, tickets=tickets))
    if not stages:
        raise argparse.ArgumentTypeError("At least one stage is required")
    return stages


def default_project_key() -> str:
    suffix = int(time.time()) % 1000000
    return f"LT{suffix}"


def validate_project_key(value: str) -> str:
    key = value.strip().upper()
    if not PROJECT_KEY_RE.match(key):
        raise argparse.ArgumentTypeError("Project key must be 2-10 uppercase letters/digits")
    return key


async def authenticate(client: httpx.AsyncClient, args: argparse.Namespace) -> str:
    if args.session_cookie:
        client.cookies.set("roundtable_session", args.session_cookie)

    if args.dev_login:
        response = await client.post(
            "/auth/dev",
            data={"login": args.dev_login, "email": f"{args.dev_login}@load.local"},
            follow_redirects=True,
        )
        response.raise_for_status()

    if args.csrf_token:
        return args.csrf_token

    response = await client.get("/projects")
    response.raise_for_status()
    match = CSRF_RE.search(response.text)
    if not match:
        raise RuntimeError(
            "Could not discover CSRF token. Use --dev-login locally or pass "
            "--session-cookie and --csrf-token for an existing session."
        )
    return match.group(1)


async def ensure_project(client: httpx.AsyncClient, csrf: str, args: argparse.Namespace) -> None:
    if args.no_create_project:
        return
    response = await client.post(
        "/api/projects",
        data={
            "csrf_token": csrf,
            "key": args.project_key,
            "name": args.project_name,
            "description": "RoundTable load-test project. Safe to delete after testing.",
            "repo": "",
        },
        follow_redirects=False,
    )
    if response.status_code in {303, 400}:
        # 400 usually means the project already exists. Keep going because this
        # runner is often used in several small waves against the same project.
        return
    response.raise_for_status()


def ticket_payload(csrf: str, project_key: str, sequence: int, virtual_user: int) -> dict[str, str]:
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    return {
        "csrf_token": csrf,
        "project_key": project_key,
        "title": f"Load ticket {sequence:06d} by vu-{virtual_user}",
        "description": f"Generated by tools/load_test.py at {now}.",
        "ticket_type": "Task",
        "priority": "Medium",
        "story_points": str(sequence % 8),
        "assignee_id": "",
        "sprint_id": "",
    }


async def create_ticket(
    client: httpx.AsyncClient,
    csrf: str,
    project_key: str,
    sequence: int,
    virtual_user: int,
) -> tuple[bool, float, str]:
    started = time.perf_counter()
    try:
        response = await client.post(
            "/api/tickets",
            data=ticket_payload(csrf, project_key, sequence, virtual_user),
            follow_redirects=False,
        )
        elapsed_ms = (time.perf_counter() - started) * 1000
        if response.status_code in {200, 303}:
            return True, elapsed_ms, ""
        return False, elapsed_ms, f"HTTP {response.status_code}: {response.text[:160]}"
    except Exception as exc:  # noqa: BLE001 - report and stop by thresholds.
        elapsed_ms = (time.perf_counter() - started) * 1000
        return False, elapsed_ms, repr(exc)


async def run_stage(client: httpx.AsyncClient, csrf: str, args: argparse.Namespace, stage: Stage) -> StageResult:
    result = StageResult(stage=stage)
    queue: asyncio.Queue[int] = asyncio.Queue()
    for sequence in range(1, stage.tickets + 1):
        queue.put_nowait(sequence)

    async def worker(worker_id: int) -> None:
        while True:
            try:
                sequence = queue.get_nowait()
            except asyncio.QueueEmpty:
                return
            ok, elapsed_ms, error = await create_ticket(
                client,
                csrf,
                args.project_key,
                sequence + args.sequence_offset,
                worker_id,
            )
            result.latencies_ms.append(elapsed_ms)
            if ok:
                result.ok += 1
            else:
                result.errors += 1
                if args.verbose:
                    print(f"  error: {error}")
            if args.min_delay_ms:
                await asyncio.sleep(args.min_delay_ms / 1000)

    await asyncio.gather(*(worker(i + 1) for i in range(stage.concurrency)))
    return result


def print_plan(args: argparse.Namespace, stages: Iterable[Stage]) -> None:
    print("RoundTable load plan")
    print(f"  target:       {args.base_url}")
    print(f"  project:      {args.project_key}")
    print(f"  create proj:  {not args.no_create_project}")
    print(f"  thresholds:   error_rate <= {args.max_error_rate:.1%}, p95 <= {args.max_p95_ms:.0f} ms")
    print(f"  delay:        {args.min_delay_ms} ms/request/worker, cooldown {args.cooldown_s}s")
    for index, stage in enumerate(stages, start=1):
        print(f"  stage {index}:    concurrency={stage.concurrency}, tickets={stage.tickets}")


async def amain() -> int:
    parser = argparse.ArgumentParser(description="Cautious RoundTable HTTP load runner")
    parser.add_argument("--base-url", default=os.getenv("ROUNDTABLE_BASE_URL", "http://127.0.0.1:8000"))
    parser.add_argument("--project-key", default=os.getenv("ROUNDTABLE_LOAD_PROJECT", default_project_key()), type=validate_project_key)
    parser.add_argument("--project-name", default="RoundTable Load Test")
    parser.add_argument("--stages", default="1x5,2x10", type=parse_stages)
    parser.add_argument("--dev-login", default=os.getenv("ROUNDTABLE_DEV_LOGIN", "load_admin"))
    parser.add_argument("--session-cookie", default=os.getenv("ROUNDTABLE_SESSION", ""))
    parser.add_argument("--csrf-token", default=os.getenv("ROUNDTABLE_CSRF", ""))
    parser.add_argument("--no-create-project", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--timeout-s", type=float, default=10.0)
    parser.add_argument("--cooldown-s", type=float, default=5.0)
    parser.add_argument("--min-delay-ms", type=float, default=75.0)
    parser.add_argument("--max-error-rate", type=float, default=0.02)
    parser.add_argument("--max-p95-ms", type=float, default=1500.0)
    parser.add_argument("--sequence-offset", type=int, default=0)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    print_plan(args, args.stages)
    if args.dry_run:
        return 0

    if args.base_url.startswith("https://") and args.dev_login and not args.session_cookie:
        raise SystemExit(
            "Refusing dev-login against HTTPS target. Pass --session-cookie and --csrf-token explicitly."
        )

    async with httpx.AsyncClient(base_url=args.base_url.rstrip("/"), timeout=args.timeout_s) as client:
        csrf = await authenticate(client, args)
        await ensure_project(client, csrf, args)

        for index, stage in enumerate(args.stages, start=1):
            started = time.perf_counter()
            result = await run_stage(client, csrf, args, stage)
            duration = time.perf_counter() - started
            rate = result.ok / duration if duration else 0
            print(
                "stage %s done: ok=%s errors=%s error_rate=%.1f%% avg=%.0fms p95=%.0fms rate=%.2f/s"
                % (
                    index,
                    result.ok,
                    result.errors,
                    result.error_rate * 100,
                    result.avg_ms,
                    result.p95_ms,
                    rate,
                )
            )
            if result.error_rate > args.max_error_rate:
                print("stop: error rate exceeded")
                return 2
            if result.p95_ms > args.max_p95_ms:
                print("stop: p95 latency exceeded")
                return 3
            if index != len(args.stages):
                await asyncio.sleep(args.cooldown_s)
    return 0


def main() -> None:
    raise SystemExit(asyncio.run(amain()))


if __name__ == "__main__":
    main()
